apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: solar-app-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/sanjeevk9/argocd.git
      revision: HEAD
      directories:
      - path: apps/*
      - path: declarative
        exclude: true
      - path: apps/solar-system2
        exclude: true
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "my-project"
      source:
        repoURL: https://github.com/sanjeevk9/argocd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated: {}