apiVersion: v1
kind: Service
metadata:
  labels:
    app: solar-system2
  name: solar-system-service2
  namespace: solar-system
spec:
  ports:
  - port: 80 #change to 80
    protocol: TCP
    targetPort: 80 #change to 80
    nodePort: 30335
  selector:
    app: solar-system2
  type: NodePort
